basketball_game/basketball_game/urls.py
from django.contrib import admin
from django.urls import path, include
from basketball_game_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.Base.as_view(), name='base'),

    path('all-teams/', views.AllTeamsView.as_view(), name='all-teams'),
    path('team/<int:pk>/', views.TeamDetailView.as_view(), name='team-detail'),
    path('add-team/', views.TeamCreate.as_view(), name='add-team'),
    path('edit-team/<int:pk>/', views.TeamUpdate.as_view(), name='edit-team'),
    path('delete-team/<int:pk>/', views.TeamDelete.as_view(), name='delete-team'),

    path('all-players/', views.AllPlayersView.as_view(), name='all-players'),
    path('team-players/<int:team_id>', views.TeamPlayersView.as_view(), name='team-players'),
    path('player/<int:pk>/', views.PlayerDetailView.as_view(), name='player-detail'),
    path('add-player/', views.PlayerCreate.as_view(), name='add-player'),
    path('edit-player/<int:pk>/', views.PlayerUpdate.as_view(), name='edit-player'),
    path('delete-player/<int:pk>/', views.PlayerDelete.as_view(), name='delete-player'),

    path('new-game/', views.NewGameView.as_view(), name='new-game'),
    path('game/<int:pk>/<int:quarter>', views.GameView.as_view(), name='game-view'),
    path('all-games/', views.AllGamesView.as_view(), name='all-games'),
    path('game-detail/<int:pk>/', views.GameDetailView.as_view(), name='game-detail'),

    path('save-team-stats/', views.SaveTeamStats.as_view(), name='save-team-stats'),
    path('get-team-stats/', views.GetTeamStats.as_view(), name='get-team-stats'),
]

basketball_game/basketball_game_app/models.py
from django.db import models

from datetime import date


class Group(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Teams(models.Model):
    name = models.CharField(max_length=64)
    games_played = models.IntegerField(default=0)
    games_won = models.IntegerField(default=0)
    conference = models.ForeignKey(Group, on_delete=models.DO_NOTHING, null=True)

    @property
    def games_lost(self):
        return self.games_played - self.games_won

    @property
    def wins_percentage(self):
        return round(self.games_won / self.games_played, 3)

    def __str__(self):
        return self.name


class Players(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=128)
    date_of_birth = models.DateField()
    team = models.ForeignKey(Teams, on_delete=models.SET_NULL, null=True)

    @property
    def age(self):
        now = date.today()
        if now.month > self.date_of_birth.month or (
                now.month == self.date_of_birth.month and now.day >= self.date_of_birth.day):
            age = now.year - self.date_of_birth.year
        else:
            age = now.year - self.date_of_birth.year - 1
        return age

    def __str__(self):
        return f'{self.last_name} {self.first_name}, {self.team}'


class Games(models.Model):
    date = models.DateField()
    team_home = models.ForeignKey(Teams, on_delete=models.SET_NULL, null=True, related_name='home_games')
    team_away = models.ForeignKey(Teams, on_delete=models.SET_NULL, null=True, related_name='away_games')
    team_home_score = models.IntegerField(null=True)
    team_away_score = models.IntegerField(null=True)

    def get_team_home_stats(self):
        return self.teamstats_set.filter(team=self.team_home)

    def get_team_away_stats(self):
        return self.teamstats_set.filter(team=self.team_away)

    def __str__(self):
        return f'{self.date}, {self.team_home} vs {self.team_away}'


class Part(models.Model):
    choices = (
        (1, 'Q1'),
        (2, 'Q2'),
        (3, 'Q3'),
        (4, 'Q4'),
        (5, 'OT'),
    )
    game = models.ForeignKey(Games, on_delete=models.CASCADE)
    name = models.IntegerField(choices=choices)
    score_team_home = models.IntegerField()
    score_team_away = models.IntegerField()


class Stats(models.Model):
    game = models.ForeignKey(Games, on_delete=models.CASCADE)

    three_pointers_made = models.IntegerField(default=0)
    three_pointers_attempted = models.IntegerField(default=0)
    two_pointers_made = models.IntegerField(default=0)
    two_pointers_attempted = models.IntegerField(default=0)
    free_throws_made = models.IntegerField(default=0)
    free_throws_attempted = models.IntegerField(default=0)

    off_rebounds = models.IntegerField(default=0)
    def_rebounds = models.IntegerField(default=0)

    assists = models.IntegerField(default=0)
    steals = models.IntegerField(default=0)
    blocks = models.IntegerField(default=0)
    turnovers = models.IntegerField(default=0)

    personal_fouls = models.IntegerField(default=0)
    technical_fouls = models.IntegerField(default=0)

    @property
    def total_rebounds(self):
        return self.off_rebounds + self.def_rebounds

    @property
    def points(self):
        return self.free_throws_made * 1 + self.two_pointers_made * 2 + self.three_pointers_made * 3

    @property
    def fg_percentage(self):
        if self.three_pointers_attempted + self.two_pointers_attempted == 0:
            return 0
        return round((self.three_pointers_made + self.two_pointers_made) / (
                self.three_pointers_attempted + self.two_pointers_attempted), 2)

    @property
    def ft_percentage(self):
        if self.free_throws_attempted == 0:
            return 0
        return round(self.free_throws_made / self.free_throws_attempted, 2)

    @property
    def p3_percentage(self):
        if self.three_pointers_attempted == 0:
            return 0
        return round(self.three_pointers_made / self.three_pointers_attempted, 2)

    class Meta:
        abstract = True


class PlayerStats(Stats):
    player = models.ForeignKey(Players, on_delete=models.SET_NULL, null=True)
    minutes_played = models.IntegerField(default=0)


class TeamStats(Stats):
    team = models.ForeignKey(Teams, on_delete=models.SET_NULL, null=True)

basketball_game/basketball_game_app/forms.py
from django import forms
from basketball_game_app.models import (
    Games,
)


class NewGameForm(forms.ModelForm):
    class Meta:
        model = Games
        exclude = ['team_home_score', 'team_away_score']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'] = forms.DateField(
            widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        )

    def clean(self):
        cleaned_data = super().clean()
        team_1 = cleaned_data.get('team_home')
        team_2 = cleaned_data.get('team_away')
        if team_1 == team_2:
            raise forms.ValidationError('You chose the same team twice')

basketball_game/basketball_game_app/views.py
from datetime import date

from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (DetailView,
                                  DeleteView,
                                  UpdateView,
                                  CreateView,
                                  )

from basketball_game_app.forms import NewGameForm
from basketball_game_app.validators import validate_positive_int
from basketball_game_app.models import (Teams,
                                        Players,
                                        Games,
                                        Group,
                                        Part,
                                        TeamStats,
                                        )


class Base(View):
    def get(self, request):
        return render(request, 'basketball_game_app/base.html')


class AllTeamsView(View):
    def get(self, request):
        eastern_conference = Teams.objects.filter(conference_id=1).order_by("-games_won", "games_played")
        western_conference = Teams.objects.filter(conference_id=2).order_by("-games_won", "games_played")
        return render(request, 'basketball_game_app/all_teams.html',
                      context={'east': eastern_conference, 'west': western_conference})


class TeamDetailView(DetailView):
    model = Teams


class TeamCreate(CreateView):
    model = Teams
    fields = '__all__'
    template_name = 'basketball_game_app/add_team.html'
    success_url = reverse_lazy('all-teams')


class TeamUpdate(UpdateView):
    model = Teams
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('all-teams')


class TeamDelete(DeleteView):
    model = Teams
    template_name = 'basketball_game_app/delete_form.html'
    success_url = reverse_lazy('all-teams')


class PlayerDetailView(DetailView):
    model = Players


class PlayerCreate(CreateView):
    model = Players
    fields = '__all__'
    template_name = 'basketball_game_app/add_player.html'
    success_url = reverse_lazy('all-players')


class PlayerUpdate(UpdateView):
    model = Players
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('all-players')


class AllPlayersView(View):
    def get(self, request):
        all_players = Players.objects.all().order_by('last_name')
        teams = Teams.objects.all()
        groups = Group.objects.all()
        return render(request, 'basketball_game_app/all_players.html',
                      context={'players': all_players, 'teams': teams, 'groups': groups})


class TeamPlayersView(View):
    def get(self, request, team_id):
        team_players = Players.objects.filter(team_id=team_id).order_by('last_name')
        teams = Teams.objects.all()
        groups = Group.objects.all()
        return render(request, 'basketball_game_app/all_players.html',
                      context={'players': team_players, 'teams': teams, 'groups': groups, 'team_id': team_id})

class PlayerDelete(DeleteView):
    model = Players
    template_name = 'basketball_game_app/delete_form.html'
    success_url = reverse_lazy('all-players')


class NewGameView(View):

    def get(self, request):
        today = date.today()
        form = NewGameForm(initial={'date': today})
        return render(request, 'basketball_game_app/new_game_form.html', {'form': form})

    def post(self, request):
        form = NewGameForm(request.POST)
        if form.is_valid():
            game = form.save()
            return redirect('game-view', game.id, 1)
        return render(request, 'basketball_game_app/new_game_form.html', {'form': form})


class GameView(View):

    def get(self, request, pk, quarter):
        game = Games.objects.get(id=pk)
        team_home_score_total = request.session.get('team_home_score_total')
        team_away_score_total = request.session.get('team_away_score_total')
        if team_away_score_total is None or quarter == 1:
            team_away_score_total = 0
        if team_home_score_total is None or quarter == 1:
            team_home_score_total = 0
        return render(request, 'basketball_game_app/game.html',
                      context={'game_data': game, 'quarter': quarter, 'team_home_score_total': team_home_score_total,
                               'team_away_score_total': team_away_score_total})

    def post(self, request, pk, quarter):
        game = Games.objects.get(id=pk)
        team_home = game.team_home
        team_away = game.team_away
        # quarter score
        team_home_score = request.POST.get('team_home_score')
        team_away_score = request.POST.get('team_away_score')
        if not (validate_positive_int(team_away_score) and validate_positive_int(team_home_score)):
            return self.get(request, pk, quarter)
        team_away_score = int(team_away_score)
        team_home_score = int(team_home_score)
        # game score
        team_home_score_total = request.POST.get('team_home_score_total')
        team_away_score_total = request.POST.get('team_away_score_total')
        if not (validate_positive_int(team_away_score_total) and validate_positive_int(team_home_score_total)):
            return self.get(request, pk, quarter)
        team_away_score_total = int(team_away_score_total)
        team_home_score_total = int(team_home_score_total)
        request.session['team_home_score_total'] = team_home_score_total
        request.session['team_away_score_total'] = team_away_score_total
        # team stats
        team_home_score_total = request.POST.get('team_home_score_total')
        team_away_score_total = request.POST.get('team_away_score_total')
        if not (validate_positive_int(team_away_score_total) and validate_positive_int(team_home_score_total)):
            return self.get(request, pk, quarter)
        team_away_score_total = int(team_away_score_total)
        team_home_score_total = int(team_home_score_total)
        request.session['team_home_score_total'] = team_home_score_total
        request.session['team_away_score_total'] = team_away_score_total
        # saving quarter
        new_quarter = Part()
        new_quarter.game = game
        new_quarter.name = quarter
        new_quarter.score_team_away = team_away_score
        new_quarter.score_team_home = team_home_score
        new_quarter.save()
        if quarter < 5:
            quarter += 1
        if quarter > 4 and team_away_score_total != team_home_score_total:
            game.team_away_score = team_away_score_total
            game.team_home_score = team_home_score_total
            game.save()
            team_home.games_played += 1
            team_away.games_played += 1
            if team_home_score_total > team_away_score_total:
                team_home.games_won += 1
            elif team_away_score_total > team_home_score_total:
                team_away.games_won += 1
            team_away.save()
            team_home.save()
            return redirect('all-games')
        return redirect('game-view', pk, quarter)


class AllGamesView(View):
    def get(self, request):
        all_games = Games.objects.all().order_by('-date', '-id')
        return render(request, 'basketball_game_app/all_games.html', context={'games': all_games})


class GameDetailView(DetailView):
    model = Games


class SaveTeamStats(View):
    def get(self, request):
        pass

    def post(self, request):
        game_id = request.POST.get("game_id")
        if not (validate_positive_int(game_id)):
            return False
        game_id = int(game_id)
        game = Games.objects.get(id=game_id)
        update_team = request.POST.get('team')
        if update_team == "home":
            team = Teams.objects.get(id=game.team_home_id)
        elif update_team == "away":
            team = Teams.objects.get(id=game.team_away_id)
        stat_name = request.POST.get('stat_name')
        try:
            stats_obj = get_object_or_404(TeamStats, game_id=game_id, team=team)
        except Http404:
            stats_obj = TeamStats.objects.create(game=game, team=team)
        finally:
            if stat_name == "3Pm":
                stats_obj.three_pointers_attempted += 1
                stats_obj.three_pointers_made += 1
            elif stat_name == "2Pm":
                stats_obj.two_pointers_attempted += 1
                stats_obj.two_pointers_made += 1
            elif stat_name == "FTm":
                stats_obj.free_throws_attempted += 1
                stats_obj.free_throws_made += 1
            elif stat_name == "3Pa":
                stats_obj.three_pointers_attempted += 1
            elif stat_name == "2Pa":
                stats_obj.two_pointers_attempted += 1
            elif stat_name == "FTa":
                stats_obj.free_throws_attempted += 1
            elif stat_name == "OffReb":
                stats_obj.off_rebounds += 1
            elif stat_name == "DefReb":
                stats_obj.def_rebounds += 1
            elif stat_name == "Ast":
                stats_obj.assists += 1
            elif stat_name == "Stl":
                stats_obj.steals += 1
            elif stat_name == "Blk":
                stats_obj.blocks += 1
            elif stat_name == "Tov":
                stats_obj.turnovers += 1
            elif stat_name == "PF":
                stats_obj.personal_fouls += 1
            elif stat_name == "TF":
                stats_obj.technical_fouls += 1
            stats_obj.save()
            data = {'stats_obj': 'saved'}
        return JsonResponse(data)


class GetTeamStats(View):
    def get(self, request):
        game_id = request.GET.get("game_id")
        game = Games.objects.get(id=game_id)
        update_team = request.GET.get('team')
        if update_team == "home":
            team = game.team_home
        elif update_team == "away":

basketball_game/templates/basketball_game_app/add_player.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="form-div">
        <h2>Add new player</h2>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/all_games.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="content-list">
        <ul>
            {% for game in games %}
                <li><a href="{% url 'game-detail' game.id %}">{{ game }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/all_players.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="content-list">
        <select id="players-team">
            <option value="all">---all---</option>
            {% for team in teams %}
                {% if team.id == team_id %}
                <option value="{{ team.id }}" selected>{{ team }}</option>
                {% else %}
                <option value="{{ team.id }}">{{ team }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <ul>
            {% for player in players %}
                <li><a href="{% url 'player-detail' player.id %}">{{ player }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% load static %}
    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="{% static "js/all-players.js" %}"></script>
{% endblock %}

basketball_game/templates/basketball_game_app/all_teams.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="league-tables">
        <div class="conference">
            <h3>Eastern conference</h3>
            <table>
                <tr>
                    <td>TEAM</td>
                    <td>GP</td>
                    <td>GW</td>
                    <td>GL</td>
                    <td>WIN%</td>
                </tr>
                {% for team in east %}
                    <tr>
                        <td>
                            <a href="{% url 'team-detail' team.id %}">{{ team.name }}</a>
                        </td>
                        <td>
                            {{ team.games_played }}
                        </td>
                        <td>
                            {{ team.games_won }}
                        </td>
                        <td>
                            {{ team.games_lost }}
                        </td>
                        <td>
                            {% if team.games_played == 0 %}
                                --
                            {% else %}
                                {{ team.wins_percentage }}
                            {% endif %}
                        </td>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="conference">
            <h3>Western conference</h3>
            <table>
                <tr>
                    <td>TEAM</td>
                    <td>GP</td>
                    <td>GW</td>
                    <td>GL</td>
                    <td>WIN%</td>
                </tr>
                {% for team in west %}
                    <tr>
                        <td>
                            <a href="{% url 'team-detail' team.id %}">{{ team.name }}</a>
                        </td>
                        <td>
                            {{ team.games_played }}
                        </td>
                        <td>
                            {{ team.games_won }}
                        </td>
                        <td>
                            {{ team.games_lost }}
                        </td>
                        <td>
                            {% if team.games_played == 0 %}
                                --
                            {% else %}
                                {{ team.wins_percentage }}
                            {% endif %}
                        </td>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/all-teams.css' %}">
{% endblock %}

basketball_game/templates/basketball_game_app/alll_teams.html
<h3>Eastern conference</h3>
<table>
<tr>
    <td>TEAM</td>
    <td>GP</td>
    <td>GW</td>
    <td>GL</td>
    <td>WIN%</td>
</tr>
    {% for team in east %}
            <tr>
                <td>
                    {{ team.name }}
                </td>
                <td>
                    {{ team.games_played }}
                </td>
                <td>
                    {{ team.games_won }}
                </td>
                <td>
                    {{ team.games_lost }}
                </td>
                <td>
                    {% if team.games_played == 0 %}
                        0
                    {% else %}
                        {{ team.wins_percentage }}
                    {% endif %}
                </td>
                </td>
            </tr>
{% endfor %}
</table>
<h3>Western conference</h3>
<table>
<tr>
    <td>TEAM</td>
    <td>GP</td>
    <td>GW</td>
    <td>GL</td>
    <td>WIN%</td>
</tr>
    {% for team in west %}
            <tr>
                <td>
                    {{ team.name }}
                </td>
                <td>
                    {{ team.games_played }}
                </td>
                <td>
                    {{ team.games_won }}
                </td>
                <td>
                    {{ team.games_lost }}
                </td>
                <td>
                    {% if team.games_played == 0 %}
                        0
                    {% else %}
                        {{ team.wins_percentage }}
                    {% endif %}
                </td>
                </td>
            </tr>
{% endfor %}
</table>

basketball_game/templates/basketball_game_app/base.html
{% extends 'basketball_game_app/menu.html' %}
{% block base %}
    <p>
    <h2>
        Welcome to basketball games management system
    </h2>
    </p>
{% endblock %}

basketball_game/templates/basketball_game_app/delete_form.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="form-div">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/games_detail.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <p><strong>{{ object }}</strong></p>
    <table>
        <tr>
            <th>TEAM</th>
            {% for part in object.part_set.all %}
                {% if part.name < 5 %}
                    <th>Q{{ part.name }}</th>
                {% else %}
                    <th>OT</th>
                {% endif %}
            {% endfor %}
            <th>
                Total
            </th>
        </tr>
        <tr>
            <th>{{ object.team_home }}</th>
            {% for part in object.part_set.all %}
                <td>{{ part.score_team_home }}</td>
            {% endfor %}
            <th>
                {{ object.team_home_score }}
            </th>
        </tr>
        <tr>
            <th>{{ object.team_away }}</th>
            {% for part in object.part_set.all %}
                <td>{{ part.score_team_away }}</td>
            {% endfor %}
            <th>
                {{ object.team_away_score }}
            </th>
        </tr>
    </table>
    <table class="team_stats">
        <tr>
            <th>TEAM</th>
            <th>SCORE</th>
            <th>FGm</th>
            <th>FGa</th>
            <th>FG%</th>
            <th>3Pm</th>
            <th>3Pa</th>
            <th>3P%</th>
            <th>FTm</th>
            <th>FTa</th>
            <th>FT%</th>
            <th>REB</th>
            <th>OREB</th>
            <th>DREB</th>
            <th>AST</th>
            <th>STL</th>
            <th>BLK</th>
            <th>TOV</th>
            <th>PF</th>
            <th>TF</th>
        </tr>
        <tr>

            <th>{{ object.team_home }}</th>
            <th>{{ object.get_team_home_stats.get.points }}</th>
            <td>{{ object.get_team_home_stats.get.two_pointers_made|add:object.get_team_home_stats.get.three_pointers_made }}</td>
            <td>{{ object.get_team_home_stats.get.two_pointers_attempted|add:object.get_team_home_stats.get.three_pointers_attempted }}</td>
            <td>{{ object.get_team_home_stats.get.fg_percentage }}</td>
            <td>{{ object.get_team_home_stats.get.three_pointers_made }}</td>
            <td>{{ object.get_team_home_stats.get.three_pointers_attempted }}</td>
            <td>{{ object.get_team_home_stats.get.p3_percentage }}</td>
            <td>{{ object.get_team_home_stats.get.free_throws_made }}</td>
            <td>{{ object.get_team_home_stats.get.free_throws_attempted }}</td>
            <td>{{ object.get_team_home_stats.get.ft_percentage }}</td>
            <td>{{ object.get_team_home_stats.get.total_rebounds }}</td>
            <td>{{ object.get_team_home_stats.get.off_rebounds }}</td>
            <td>{{ object.get_team_home_stats.get.def_rebounds }}</td>
            <td>{{ object.get_team_home_stats.get.assists }}</td>
            <td>{{ object.get_team_home_stats.get.steals }}</td>
            <td>{{ object.get_team_home_stats.get.blocks }}</td>
            <td>{{ object.get_team_home_stats.get.turnovers }}</td>
            <td>{{ object.get_team_home_stats.get.personal_fouls }}</td>
            <td>{{ object.get_team_home_stats.get.technical_fouls }}</td>
        </tr>
        <tr>
            <th>{{ object.team_away }}</th>
            <th>{{ object.get_team_away_stats.get.points }}</th>
            <td>{{ object.get_team_away_stats.get.two_pointers_made|add:object.get_team_away_stats.get.three_pointers_made }}</td>
            <td>{{ object.get_team_away_stats.get.two_pointers_attempted|add:object.get_team_away_stats.get.three_pointers_attempted }}</td>
            <td>{{ object.get_team_away_stats.get.fg_percentage }}</td>
            <td>{{ object.get_team_away_stats.get.three_pointers_made }}</td>
            <td>{{ object.get_team_away_stats.get.three_pointers_attempted }}</td>
            <td>{{ object.get_team_away_stats.get.p3_percentage }}</td>
            <td>{{ object.get_team_away_stats.get.free_throws_made }}</td>
            <td>{{ object.get_team_away_stats.get.free_throws_attempted }}</td>
            <td>{{ object.get_team_away_stats.get.ft_percentage }}</td>
            <td>{{ object.get_team_away_stats.get.total_rebounds }}</td>
            <td>{{ object.get_team_away_stats.get.off_rebounds }}</td>
            <td>{{ object.get_team_away_stats.get.def_rebounds }}</td>
            <td>{{ object.get_team_away_stats.get.assists }}</td>
            <td>{{ object.get_team_away_stats.get.steals }}</td>
            <td>{{ object.get_team_away_stats.get.blocks }}</td>
            <td>{{ object.get_team_away_stats.get.turnovers }}</td>
            <td>{{ object.get_team_away_stats.get.personal_fouls }}</td>
            <td>{{ object.get_team_away_stats.get.technical_fouls }}</td>
        </tr>
    </table>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/game-detail.css' %}">
{% endblock %}

basketball_game/templates/basketball_game_app/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basketball</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>
<body>

<div class="menu">
    <ul>
        <li class="menu"><a class="menu" href="{% url 'all-games' %}">All games</a></li>
        <li class="menu"><a class="menu" href="{% url 'all-teams' %}">All teams</a></li>
        <li class="menu"><a class="menu" href="{% url 'all-players' %}">All players</a></li>
        <li class="menu"><a class="menu" href="{% url 'add-team' %}">Add team</a></li>
        <li class="menu"><a class="menu" href="{% url 'add-player' %}">Add player</a></li>
        <li class="menu"><a class="menu" href="{% url 'new-game' %}">New game</a></li>
    </ul>
</div>
{% block base %}

{% endblock %}
{% block content %}

{% endblock %}
</body>
</html>

basketball_game/templates/basketball_game_app/new_game_form.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="form-div">
        <h2>New game</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="start">
        </form>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/players_update_form.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="form-div">
        <h3>Edit player</h3>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="reset" value="Reset">
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/teams_detail.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="detail-div">
        <h2>{{ object.name }}</h2>
        <p>
            <strong>Conference </strong>{{ object.conference }}
        </p>
        <p>
            <strong>Games played </strong>{{ object.games_played }}
        </p>
        <p>
            <strong>Wins </strong>{{ object.games_won }}
        </p>
        <p>
            <strong>Losses </strong>{{ object.games_lost }}
        </p>
        <p>
            <strong>Win % </strong>{% if object.games_played == 0 %}--{% else %}{{ object.wins_percentage }}{% endif %}
        </p>
        <a href="{% url 'edit-team' object.id %}">edit</a>
        <a href="{% url 'delete-team' object.id %}">delete</a>
    </div>
{% endblock %}

basketball_game/templates/basketball_game_app/teams_update_form.html
{% extends 'basketball_game_app/menu.html' %}
{% block content %}
    <div class="form-div">
        <h3>Edit team</h3>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="reset" value="Reset">
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}